services:
  front-login-home:
    profiles:
      - docker-fronts

  front-escritorio:
    profiles:
      - docker-fronts

  front-silo:
    profiles:
      - docker-fronts

  core-service:
    environment:
      DB_SYNC_ALTER: "true"

  escritorio-service:
    environment:
      DB_SYNC_ALTER: "true"

  silo-service:
    environment:
      DB_SYNC_ALTER: "true"

  swagger-service:
    environment:
      CORE_OPENAPI_URL: http://core-service:3000/openapi.json
      ESCRITORIO_OPENAPI_URL: http://escritorio-service:3000/openapi.json
      SILO_OPENAPI_URL: http://silo-service:3000/openapi.json

  nginx:
    depends_on:
      - core-service
      - escritorio-service
      - silo-service
      - swagger-service
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
